### ISSUE TITLE
New preview does not work with Vorto values

### ISSUE THREAD

**Issue by tomvanenckevort** [skttl/umbraco-doc-type-grid-editor#117]
We were trying out the 0.6.0 beta today to see if the fix for unpublished content previews works.
Unfortunately it looks like there is a different issue now to do with Vorto values in the DTGE doc type.

When in the new preview mode the GetVortoValue method always returns null, whereas if I view the same page on the frontend the same method call returns the right value.
I can see the property and value are there when in preview mode, it's just the conversion that fails.
I'm wondering whether it has something to do with the [check](https://github.com/umco/umbraco-vorto/blob/5f39ad7a1113c9b371e8ceb488cb1ec728bfa444/src/Our.Umbraco.Vorto/Extensions/IPublishedContentExtensions.cs#L137) for the preview mode in GetVortoValue no longer working (since you're bypassing the default Umbraco preview mode).

So to reproduce the issue:

1. Create a doc type containing at least one Vorto property (using a simple textstring will be enough) and one normal property (again, simple textstring will do).
2. Create a view partial for the new doc type and write out both properties (the Vorto one using the `GetVortoValue` method).
3. Add it to the DTGE editor config (using the default settings, no separate preview partial view).
4. Add the newly added doctype as a module to a grid on a new page.
5. Add some text in the doc type fields.
6. Save and publish the page.
7. View the page normally (not in preview mode) in the browser and confirm that both property values are displayed correctly.
8. Now go back to the CMS and confirm that the preview of the grid module in the CMS is only showing the non-Vorto value.

Umbraco: v7.11.1
DTGE: v0.6.0-beta

**Comment by leekelleher** [comment]
I've added code to enable the `InPreviewMode`, in commit: 0ebaf166c4233274b6f43d6897ede5467be9f8b9
This will be part of upcoming v0.6.0 release.

**Comment by leekelleher** [comment]
Unfortunately, it appears that in setting `InPreviewMode` it causes other issues. See #124 for details.
Flagging it on here that we may need to explore other options to fix this.

**Comment by leekelleher** [comment]
@tomvanenckevort I realised that I never got confirmation on whether this fix actually worked for you or not, can you confirm if it did?

I've had to revert manually setting the `InPreviewMode` in PR #127, it was causing bugs in other areas of the preview mechanism.

**Comment by tomvanenckevort** [comment]
@leekelleher I've just tried it with v0.6.0 and the previews still return empty values for the Vorto fields. So it doesn't look like the `InPreviewMode` change was working for Vorto anyway.

**Comment by leekelleher** [comment]
Oh. Re-opening this ticket.

**Comment by skttl** [comment]
Closing this, as Vorto doesn't work for v8.
