### ISSUE TITLE
Macro inside RTE inside grid throws

### ISSUE THREAD

**Issue by StefanoChiodino** [skttl/umbraco-doc-type-grid-editor#134]
Hey, I'm on Umbraco v7.13.1 and DTGE v0.6.1 and when trying to render a form macro inside a RTE which is inside a block I get `System.InvalidOperationException: The UmbracoPage object has not been initialized yet.`

This happens when trying to get the grid field into any type (string or IHtmlString)
![image](https://user-images.githubusercontent.com/1428893/52286854-e8274e00-2960-11e9-8510-6b78cfe4fb92.png)

Would have thought someone else must have had the same but couldn't find anything about it!

Cheers!

**Comment by leekelleher** [comment]
Hi @StefanoChiodino,

Looking over the Umbraco source, I can see where the exception is being thrown from...

- https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web/UmbracoComponentRenderer.cs#L105
- https://github.com/umbraco/Umbraco-CMS/blob/dev-v7/src/Umbraco.Web/Routing/PublishedContentRequest.cs#L489

I guess you're right, no one has tried to preview a Macro within an RTE within a DTGE within the Grid before ... or they've not reported it and ended up reworking it. 😖 

I'm not sure what the exact fix is at the moment. My gut feeling is that the `UmbracoPage` property would need to be set in the preview controller code...
https://github.com/umco/umbraco-doc-type-grid-editor/blob/develop/src/Our.Umbraco.DocTypeGridEditor/Web/Controllers/DocTypeGridEditorApiController.cs#L119-L129
... Not sure how hacky that'd be, it'd need some exploration and experimenting.

**Comment by StefanoChiodino** [comment]
Thanks a lot @leekelleher !

**Comment by skttl** [comment]
Closing this as v0 is unsupported

**Comment by xdjoshuaaz** [comment]
Hi all,

I've made a commit in my fork that fixes this by calling `PublishedContentRequest.Prepare()` which internally sets the `UmbracoPage` property to a new page, based on the passed-in `PublishedContent` property. The culture needs to be passed in to avoid a `NullReferenceException` so re-used the logic already further down in the file.

The commit can be found [here](https://github.com/xdjoshuaaz/umbraco-doc-type-grid-editor/commit/8d2d47fb3f6cab54dce6b3f70aa99d220d753513#diff-c2343aa2d5bfd396957a1067499ab979). As v0 is unsupported, is it worth making a Pull Request for this change? It'd be nice to see this merged upstream.

Thanks,
Josh
