### ISSUE TITLE
Grid inside Nested Content unable to open DTGE Editor Panel after save & publish

### ISSUE THREAD

**Issue by marcond05** [skttl/umbraco-doc-type-grid-editor#140]
Hi Lee, 

This is the issue that was loosely related to #84. Related in that they share the same symptoms of not being able to open the editor panel after a single save & publish, requiring a full backoffice page refresh

**Steps to reproduce:** 
1) Create Nested Content and add a Grid to it that has a DTGE allowed doc type
2) Add the DTGE doc type / widget to a grid cell 
3) Hit Save & Publish
4) Attempt to re-open the DTGE editor panel 

Note: We have tried the most watered down Doc types with only a single text field and had the same results. 

**Result / Console**
Empty editor panel
```
Error: $scope.control.editor.config is undefined
Error: $scope.model.dialogData is undefined
```

Thanks for your response on the other ticket, by the way!
-Marc

![57544497-80005380-7325-11e9-89d4-d4cee54454e6](https://user-images.githubusercontent.com/8170842/57639469-fd260580-757d-11e9-9804-d8dfa8df0be7.png)

**Comment by skttl** [comment]
Hi @marcond05 

This seems to work in 1.0.0 on Umbraco 8.1, so I'm closing this issue.
