### ISSUE TITLE
Not compatible with uSkinned themes

### ISSUE THREAD

**Issue by cdecinkoKnight** [skttl/umbraco-doc-type-grid-editor#141]
After installing the package in our site that uses uSkinned theme, nearly all of the selections disappear.

**Comment by cdecinkoKnight** [comment]
It appears this issue happens when installing from inside Umbraco via Developer / Packages.  Not seeing the issue when installed via NuGet.

**Comment by leekelleher** [comment]
@cdecinkoKnight I've not used any uSkinned themes, so not aware of any specifics of their configuration set-up.  I'm curious if the `/config/grid.editors.config.js` contents got corrupted somehow?

---
Cross-linking to the forum thread on Our Umbraco: <https://our.umbraco.com/packages/backoffice-extensions/doc-type-grid-editor/doc-type-grid-editor-feedback/97445-after-installing-all-but-two-of-the-data-types-show-up-in-the-selector>

**Comment by cdecinkoKnight** [comment]
I'm jumping back into this.  In order to get one of my doc types to work, I had to create a basic template in the Views > Partials folder. If the template is in a subfolder it cannot be found.  Also, not sure why it wants to look for the template with _AN on the end of the name.

**Comment by skttl** [comment]
Hi @cdecinkoKnight 

Do you know how your grid editors are set up? If you have them in `/config/grid.editors.config.js` can you check if they got removed?

That would be my best guess. Which uSkinned theme are you using?
