### ISSUE TITLE
DTGE Migration Plan

### ISSUE THREAD

**Issue by leekelleher** [skttl/umbraco-doc-type-grid-editor#146]
Here is our proposed plan to transfer DTGE over to @skttl...

- [x] **GitHub**
  - [x] Add @skttl as maintainer (write access)
  - [x] Merge in PR #137 
  - [x] @skttl to delete his personal fork
  - [x] @leekelleher to transfer GitHub repo to @skttl's account
  - [x] @umco to fork @skttl's repo, updated README, then archive repo
- [x] **NuGet**
  - [x] Add @skttl as an owner
  - [x] Discuss whether we should remove UMCO ownership rights?
- [x] **AppVeyor CI**
  - [x] @skttl to set-up his own AppVeyor CI account
  - [x] Remove GitHub webhook to UMCO's AppVeyor
  - [x] Add GitHub webhook to @skttl's AppVeyor
  - [x] Update CI build links on repo README
  - [x] Explain the tagging workflow for releases
- [x] **Our Umbraco**
  - [x] Add @skttl as a collaborator on the project page
  - [x] Update repo links on project page
  - [x] Contact HQ (I assume @nul800sebastiaan?) to request ownership transfer of project page

If I have missed any steps, let me know, thanks!

**Comment by bjarnef** [comment]
In the package xml for the Umbraco package we can also add a `contributors` element with child `contributor`elements.
https://github.com/umco/umbraco-doc-type-grid-editor/blob/develop/build/package.xml

Furthermore we can also add an icon url to the Umbraco package and the NuGet package.

**Comment by leekelleher** [comment]
Closing this ticket. We've done all the steps. Migration successful!

Thank you @skttl for taking on DTGE for v8! #h5yr 🎉
