### ISSUE TITLE
Unable to horizontal scroll editor blade

### ISSUE THREAD

**Issue by cdecinkoKnight** [skttl/umbraco-doc-type-grid-editor#147]
The editor blade that appears for a grid editor does not allow scrolling left or right.  Some doc types that are wider than the blade have fields off the screen and unable to be reached.

![image](https://user-images.githubusercontent.com/46462212/62067343-564e1e80-b1e8-11e9-8ee9-c4772715aac2.png)

**Comment by skttl** [comment]
This is a bug in Umbraco, as we just use the core editorService for showing the panels.

**Comment by esn303** [comment]
Maybe setting "LargeDialog" could help with that (wider panel) for now, @cdecinkoKnight?
