### ISSUE TITLE
Doesn't work like the v7 Doc Type Grid Editor - doesn't work at all for me.

### ISSUE THREAD

**Issue by John-Blair** [skttl/umbraco-doc-type-grid-editor#152]
In the v7 version you could select a Doc Type that has a Property with a Data Type that is a Nested Content of some Doc Type e.g.
Doc Type: Accordion Section has a property Accordion of Data Type Accordion Panels.
Accordion Panels if a Nested Content of Document Type Accordion Panel.
Everything worked fine - the Accordion Section partial ran and displayed the Accordion Panels.

Now in v8 that is not possible.
The default is to allow you to select Doc Type "Accordion Panel" only and it expects a partial to exist to render it. This is because that doc type is marked as an "Element Type".
If I mark "Accordion Section" as an Element Type then I can no longer add this as a node in the content tree. Also if I mark this as an Element Type it still does not work. It produces the error

System.InvalidOperationException: Model Umbraco.Web.PublishedModels.EcAccordionSection expects argument of type Umbraco.Core.Models.PublishedContent.IPublishedContent, but got Our.Umbraco.DocTypeGridEditor.Models.DetachedPublishedElement.

**Comment by skttl** [comment]
Hi John, DTGE for v8 only allows you to use element types as grid editors, because they ARE elements 🙂

I think there has been mentioned some workarounds about using your element types as content nodes in our. Iirc, there was some fuzz about this when v8 got released.

Regarding the error message, did you rebuild models after changing to an element type?

**Comment by John-Blair** [comment]
Hi Søren, 
Thanks for the reply. 
That is disappointing news and a major breaking change from v7 of DTGE which supported any doc type. 

Was there any reason to make this Element Type restriction?  
The reason I ask is it makes this package not a viable proposition for me. 
Let me explain: I used v7 of DTGE to include complex controls into grid cells like Tabs, Accordions, Carousels etc. Now the nature of these controls is that they have a doc type with some general properties to govern the overall look e.g tab widths and heights etc, and then they have a single property which is a Nested Content of a suitable Element Type. Now the template for this doc type needs to have visibility of all the Nested Content in order to correctly display the control. Now your restriction to only supporting the Nested Content makes this package wholly  unsuitable for my needs. 

Now I was able to get my accordion to work with your package by making lots of hacks
1) All my Composition types in my Doc Type had to be switched to Element Types (so they no longer are IPublishedContent)
2) My Doc Type had to be switched to Element Type
3) I had to manually rebuild the models even though the model mode was LiveDll i.e. models should be rebuilt automatically.
4) All the content pages which use my basic accordion are broken because that type is no longer a IPublishedContent

It is just wrong from an architectural viewpoint to make my compositions and doc types element types just to make them work with your package. I think for the DTGE to be useful it needs to support all Doc Types otherwise I think the package should be renamed Element Type Grid Editor to reflect what it really is, and this would allow  someone else the opportunity to create a more general DTGE.  Thanks.

**Comment by John-Blair** [comment]
In case it is of use to anyone - I switched to using a macro in the grid cells to display my complex controls in a grid cell. It is a 1 line macro that has 1 parameter to pick the content item to be displayed in the grid cell. Works perfectly for my Accordion, Tabs, Carousels etc.  I just define these controls as child nodes of my grid section and pick the relevant node using the macro.

Macro Code:

`@inherits Umbraco.Web.Macros.PartialViewMacroPage
@{
    var contentId = Model.MacroParameters["contentId"];
    var content = Umbraco.Content(contentId);
}
@Html.Partial(content.GetTemplateAlias(), content)

`

**Comment by skttl** [comment]
Glad you found a way to make your setup work for you. Grid items IS elements, and that is not going to change.

**Comment by cleversolutions** [comment]
Thanks @skttl for your reminder to rebuild models. I ran into this error message because after changing to an element type I forgot to rebuild models. Thought I would leave a comment here for anyone who wanders by this in the future with the same error message.
