### ISSUE TITLE
Feature idea: List of docs

### ISSUE THREAD

**Issue by DesignMonkey** [skttl/umbraco-doc-type-grid-editor#153]
Hi

First of all - great package :) 

Have you considered since Archetype and LeBlender doesn't seem to support v8, that you could make an option to make it a list og docs, and not only one. 

I have a client that wants a image gallery with links on. It seems that there isn't an easy way in v8 for that. This could be the answer :) 

Just a suggestion - i'll have to hack my way through it now ;) 

/Peter

**Comment by skttl** [comment]
Hi Peter, thanks for your suggestion. I'm not completely sure what you mean. Can you show me an example?

**Comment by DesignMonkey** [comment]
Yea I can try :) 

I'll just use LeBlender package as an example. Right now your package, when you set it up in the json file, only supports a doctype in singular mode. I was thinking you could add i paramater to the json called e.g. `multiple: true` or something, and that would give the opportunity to have an Array/List/IEnumerable with the documents as value. 

Which would give this output (borrowed from LeBlender package):
![635646954725282539_9png](https://user-images.githubusercontent.com/1744747/64472178-cdb58d00-d15a-11e9-905b-eeb785eaae48.png)

In my case i could create a doctype called CarouselItem, and then put link(content picker) image (image picker) and title in there and be able to create a list of items :)

Does that make sense? :)

**Comment by skttl** [comment]
It does, but you can use Nested Content on your doctypes for this :)

**Comment by DesignMonkey** [comment]
Damn... Didn't knew that one - Have been away from Umbraco for a little while. But then your package is perfect as it is ;) 

Thanks :)
