### ISSUE TITLE
Doc types with "Allow varying by culture" do not save.

### ISSUE THREAD

**Issue by Maigaard** [skttl/umbraco-doc-type-grid-editor#154]
I had an issue with the doc type editor not saving content if "Allow varying by culture" on the property. I doubt this value would have any effect inside a grid, so i don't think it should be supported. But could be useful information in the documentation.

**Comment by skttl** [comment]
Thanks for reporting this, you are right, it does seem like the value isn't saved.

I have marked this as a bug, that needs to be fixed :)

**Comment by jesperordrup** [comment]
I think that dtge should only allow doctypes which has "Allow varying by culture" set to false. We already have variation covered on editor level?

**Comment by skttl** [comment]
Sounds like a good solution to this. Maybe we need some way of telling the user, that the document type selected (if in single type mode) can't be used, because its not an element or is varying by culture :)

**Comment by skttl** [comment]
Fixed in f5453dbddcf42fc4a87e4a8de8b40023f43ca5c5
