### ISSUE TITLE
Timeline / Info on Imagecropper / Tags Support

### ISSUE THREAD

**Issue by louisjacksonrees** [skttl/umbraco-doc-type-grid-editor#156]
Hi i was wondering, if there is any timeline on getting a fix for Imagecropper and tags for use in dtge, or at least a description of what needs to be done in order to add functional support for these data types?

**Comment by skttl** [comment]
Hi @louisjacksonrees 

They will probably never work in DTGE. Maybe in Grid2 if that ever gets done.

The reason is, that their values need a content item to interact with, and DTGEs is not content items.
