### ISSUE TITLE
Feature request: Reusable content

### ISSUE THREAD

**Issue by jesperordrup** [skttl/umbraco-doc-type-grid-editor#157]
When using DGTE with Umbraco 7 we typically solved this by using the same doc types to create content in a content area (ex. "Shared Content Elements") and then adding a picker to dgte. Problably a fairly commen approach..

We could do the same in U8. As the doctypes used for dtge are elements we just add and extra step of creating a wrapper doctype that uses the element doctype as composition. And then we're back on track.

But it would be far more elegant if DTGE suppported this somehow?  Anyone givin this much thought?

**Comment by skttl** [comment]
There was a package for v7 https://our.umbraco.com/packages/backoffice-extensions/doctype-grid-editor-reusable-content-extension/#package-gallery-2

But that would probably run into the same problem as you are, since Elements cant be created as content.

**Comment by jesperordrup** [comment]
Forgot all about that package. We didnt use it for reasons I cannot remember .. but now its incompatible for sure.

**Comment by skttl** [comment]
I have marked this as "Up for grabs", so if anyone wants to try and make this feature, you are welcome.

It's not on my priority list, but I'll be happy to accept a PR enabling this :)

**Comment by Matthew-Wise** [comment]
Achieving this using compositions. 
ModelBase - has all the properties and is an element
ModelContent- composed of ModelBase and is normal content you can create in the tree
ModelBlock - composed of ModelBase is an element and used directly in the grid.

We then have a block picker DTGE for selected the content versions. 
Views use the interface created by Models builder and the global picker routes the pages are required.

**Comment by skttl** [comment]
Closing this, as I think the effort should be done in the new core Block Editor in stead. Would love to see this feature there!
