### ISSUE TITLE
Why does NuGet package have dependency on Umbraco Core?

### ISSUE THREAD

**Issue by enkelmedia** [skttl/umbraco-doc-type-grid-editor#161]
Hi!

After performing an upgrade of my this package for Umbraco 7, i just "by habit" did a "Upgrade Package", since the Nuget-package have a dependency on Umbraco.Core an upgrade of Umbraco was also started.

I know I should have passed the right version when performing the upgrade but maybe we should concider to remote the explicit dependency on Umbraco.Core from the nuget-package.

It does not really provide any value since no one would install this package if not running Umbraco?

**Comment by skttl** [comment]
Makes sense to me, is there any downsides to removing the dependency?

**Comment by enkelmedia** [comment]
I would say that the only downside would be that we can't "force" a specific version of Umbraco so there would be no way to say that one would need at least Umbraco 8.3 to run DTGE.

Maybe the "right" solution is to have different nuget-feeds for the V7 and V8-version and then be explicit about the Umbraco.Core-dependency I guess.

**Comment by enkelmedia** [comment]
You know what, I think this is a “non”-issue, it should be up to the developer to look at the dependencies before installing a package.
