### ISSUE TITLE
DTGE with MNTP fails to save in v8

### ISSUE THREAD

**Issue by carbonsixdigitalpbm** [skttl/umbraco-doc-type-grid-editor#162]
When an Element DocType has an MNTP is added to a grid, the DTGE opens in an editing panel, but when the DTGE is submitted, nothing is saved in the Grid.  In Chrome 77 on Windows, using Umbraco 8.2.1 and DTGE 1.0.0.

Steps to reproduce

1. Create an Element DocType.  Add a multinode tree picker to it.
2. Enable the new Doc Type in a Grid Editor (add to package manifest etc etc)
3. Create a new Content Node with the Grid Editor on it
4. Add a Row and then Add Content chosing the new DTGE
5. Chose a node in the MNTP, click submit
6. Click Submit in the DTGE, focus should return to the Grid Editor on your content node.

Now if you Save & Publish the content node, nothing was saved in the DTGE with the MNTP.

Similarly if you reopen the DTGE without Save & Publish you'll see nothing was saved back into the grid.

No errors are thrown in the console in Chrome Dev Tools.

**Comment by skttl** [comment]
Thanks for reporting this, I'll check it out and get back :)

**Comment by skttl** [comment]
Hi @carbonsixdigitalpbm 

I just tried this, and I can't reproduce. See the gif, and let me know if I'm missing something.
![2019-11-12_20-39-39](https://user-images.githubusercontent.com/3726467/68704483-a9c45c80-058c-11ea-917f-7a0fe91b9dd1.gif)

**Comment by sstottelaar** [comment]
I just ran into the same issue. I managed to fix it by switch off "Allow varying by culture" for the Tree Picker. It seems it can't handle multiple languages, but this is not an issue since the Grid Layout itself is varying by culture (in my case).

**Comment by skttl** [comment]
Ok, this is from #154. "Fixed" (by disabling support for varying doctypes) in 1.1.

@carbonsixdigitalpbm was your doctypes varying by culture too?

**Comment by redmorello** [comment]
@skttl Yes they were, turning that off has fixed the issue.

**Comment by skttl** [comment]
Cool - then that settles it :)
