### ISSUE TITLE
Macro Not Rendering in Custom DocType RTE

### ISSUE THREAD

**Issue by lshandor** [skttl/umbraco-doc-type-grid-editor#163]
We created a custom doctype that can be added to the Grid on a page and this doctype contains an RTE as one of the fields.

We then created an "Insert Button" macro so a user could insert a button inline with text content directly into any RTE. 

The macro renders fine in the BackOffice when it is inserted into an RTE added directly to the grid. And it also renders in the RTE of the doctype but once the doctype is saved, the macro does not render in the Grid.

![2019-11-08_15-31-46](https://user-images.githubusercontent.com/11065786/68512060-5036f780-0245-11ea-89d9-4d121cea230b.jpg)

**Comment by skttl** [comment]
Thanks for reporting this.

Since I don't use v7 any more, I have marked this as `up-for-grabs`, so you or someone else kan send a PR with a fix.

**Comment by skttl** [comment]
Closing this as v0 is unsupported
