### ISSUE TITLE
Grid fails to load preview (Umbraco 7 - DTGE 0.6)

### ISSUE THREAD

**Issue by etharion** [skttl/umbraco-doc-type-grid-editor#164]
Umbraco v7.15.1
Doc type grid v0.6.1

Grid can't load previews of the elements inserted into the property. The URL its calls returns a code 500.

domain/1062?dtgePreview=1 returns code 500: Cannot bind source type Umbraco.Web.PublishedCache.XmlPublishedCache.XmlPublishedContent to model type Website.Extensions.Models.DocumentTypes.Lang.
Rest of the [stacktrace.txt](https://github.com/skttl/umbraco-doc-type-grid-editor/files/3863719/stacktrace.txt)

We have another site running:
Umbraco v7.10.4
Doc type grid v0.5.0

Here there are no problems, both sites run the same code in their controllers:
`public ActionResult Frontpage() {`
`  bool preview = Request.QueryString["dtgePreview"] == "1";`
`      if ( preview ) {`
`        return CurrentTemplate( CurrentPage );`
`      }`
`      return CurrentTemplate( new Lang( CurrentPage ) );`
`    }`

**Comment by skttl** [comment]
Hi @etharion

Thanks for submitting this. I have put this up for grabs, as I don't use DTGE for v7 projects anymore. So if you or someone else can find a solution, I'll be happy to merge and release a new version.

**Comment by skttl** [comment]
Closing this as v0 is unsupported
