### ISSUE TITLE
New dialog "Size" property causes manifest validation to fail

### ISSUE THREAD

**Issue by tompipe** [skttl/umbraco-doc-type-grid-editor#166]
The manifest specification dictates that the size property should be an object:

![image](https://user-images.githubusercontent.com/629719/69496215-a2c01700-0ec7-11ea-8173-ee988d506fd7.png)

Using it to specify dialog size causes a validation failure message

![image](https://user-images.githubusercontent.com/629719/69496188-6c829780-0ec7-11ea-843b-d1ce8e77bf76.png)

**Comment by skttl** [comment]
Good catch - thanks!
