### ISSUE TITLE
Feature Idea: Dictonary Items

### ISSUE THREAD

**Issue by AndersBrohus-MySupport** [skttl/umbraco-doc-type-grid-editor#168]
Hi :)

An nice feature would be that if the title could be using an Umbraco Dictonary Item if it contains an "#" :)

It works inside the dialog but not when showing in the grid :)

**Comment by skttl** [comment]
Good idea!

Since Doc Type Grid Editor doesn't render the title when showing in the grid, I think this should be a feature request for core instead.

**Comment by AndersBrohus-MySupport** [comment]
![image](https://user-images.githubusercontent.com/51318354/69616521-0a48a480-1037-11ea-8c22-cca07343c1f8.png)

So this title is set by the Core? :)

**Comment by skttl** [comment]
Thought you meant the blue one - what does that do?

**Comment by AndersBrohus-MySupport** [comment]
Oh sorry :)
I meant the "title" inside the grid :)

I don't know if we there is a service, but when we are running the function "setTitleAndDescription" on line 76 inside doctypegrideditor.controllers.js we could try and see if it contains an "#" and if it does then get an dictonary item just like the doctypes normally do :)

**Comment by skttl** [comment]
Yes, that should definitely be possible for the no-preview-preview :) I am curious on how the blue title will handle the dictionary keys though.

**Comment by AndersBrohus-MySupport** [comment]
I don't think we can change that, since it's something the grid inserts :)

**Comment by enkelmedia** [comment]
I think that this can be close after the introduction of “nameTemplate” for grid editors.

One can create a filter (or maybe there’s already some solution for this) and use this in the nameTemplate, see example below.

[
    ...
    {
        "name": "Doc Type",
        "alias": "docType",
        "view": "/App_Plugins/DocTypeGridEditor/Views/doctypegrideditor.html",
        "render": "/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditor.cshtml",
        "icon": "icon-item-arrangement",
        "config": {
            "allowedDocTypes": [...],
            "nameTemplate": "{{‘myKey’ | dicfilter}}",
            "enablePreview": true,
            "overlaySize": "medium",
            "viewPath": "/Views/Partials/Grid/Editors/DocTypeGridEditor/",
            "previewViewPath": "/Views/Partials/Grid/Editors/DocTypeGridEditor/Previews/",
            "previewCssFilePath": "",
            "previewJsFilePath": ""
        }
    },
    ...
]

**Comment by skttl** [comment]
This could probably be useful for Nested Content and listviews too, soo should be a feature request for adding a new filter in Core instead.
