### ISSUE TITLE
Can't preview of unpublished content on backend page (Umbraco v8.1.0 & DTGE v1.0.0)

### ISSUE THREAD

**Issue by narinkaew** [skttl/umbraco-doc-type-grid-editor#169]
Hi,

Is it possible to preview the content of the grid that is unpublished? It can't display preview and also get an error like this (part of them),

![image](https://user-images.githubusercontent.com/16592840/70257950-e9621b00-17bd-11ea-8820-3a43172acc7b.png)

`Possibly unhandled rejection: {"data":{"Message":"An error has occurred.","ExceptionMessage":"An item with the same key has already been added.","ExceptionType":"System.ArgumentException","StackTrace":"   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)\r\n   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)\r\n   at Our.Umbraco.DocTypeGridEditor.Models.UnpublishedContent.MapProperties(ServiceContext services)\r\n   at Our.Umbraco.DocTypeGridEditor.Models.UnpublishedContent.<>c__DisplayClass9_0.<.ctor>b__4()\r\n   at System.Lazy`1.CreateValue()\r\n   at System.Lazy`1.LazyInitValue()\r\n   at System.Lazy`1.get_Value()\r\n   at Our.Umbraco.DocTypeGridEditor.Models.UnpublishedContent.Umbraco.Core.Models.PublishedContent.IPublishedElement.get_Properties()\r\n   at Umbraco.Web.Macros.PublishedContentHashtableConverter.PopulateElementData(IPublishedElement node) in d:\\a\\1\\s\\src\\Umbraco.Web\\Macros\\PublishedContentHashtableConverter.cs:line 112\r\n   at Umbraco.Web.Macros.PublishedContentHashtableConverter..ctor(IPublishedContent doc) in d:\\a\\1\\s\\src\\Umbraco.Web\\Macros\\PublishedContentHashtableConverter.cs:line 70\r\n   at Umbraco.Web.Macros.MacroRenderer.Render(String macroAlias, IPublishedContent content, IDictionary`2 macroParams) in d:\\a\\1\\s\\src\\Umbraco.Web\\Macros\\MacroRenderer.cs:line 200\r\n   at Umbraco.Web.PropertyEditors.ValueConverters.RteMacroRenderingValueConverter.<>c__DisplayClass4_1.<RenderRteMacros>b__1(String macroAlias, Dictionary`2 macroAttributes) in d:\\a\\1\\s\\src\\Umbraco.Web\\PropertyEditors\\ValueConverters\\RteMacroRenderingValueConverter.cs:line 56\r\n   at Umbraco.Web.Macros.MacroTagParser.ParseMacros(String text, Action`1 textFoundCallback, Action`2 macroFoundCallback) in d:\\a\\1\\s\\src\\Umbraco.Web\\Macros\\MacroTagParser.cs:line 194\r\n   at Umbraco.Web.PropertyEditors.ValueConverters.RteMacroRenderingValueConverter.RenderRteMacros(String source, Boolean preview) in d:\\a\\1\\s\\src\\Umbraco.Web\\PropertyEditors\\ValueConverters\\RteMacroRenderingValueConverter.cs:line 51\r\n  `

---------------------------------
In case of preview on the published node, it can display preview on the backend.

![image](https://user-images.githubusercontent.com/16592840/70258386-bff5bf00-17be-11ea-900e-a0f58e8d0044.png)

I would like to preview the content in real time (even if i can see on the preview mode).
Do you have any suggest?

Thanks in advance,
narinkaew

**Comment by skttl** [comment]
Just tried on 8.1.0, with a newly created page, not even saved or published, and the preview works.

What is in your doctype?

**Comment by narinkaew** [comment]
After looking into "getEditorMarkupForDocTypePartial" which send data to "/DocTypeGridEditorApi/GetPreviewMarkup?dtgePreview=1&pageId=" + pageId", it must be "IPublishedElement" model.

So my model which generate from DocTypeGridEditor which is "Our.Umbraco.DocTypeGridEditor.Models.UnpublishedContent" doesn't support and throw the error. I just curious why is that. Anyway I will find another solution.

@alandraper Thank for your infomation.

Thanks,
