### ISSUE TITLE
Required fields not working in version 0.5.0 on Umbraco version 7.5.9 assembly: 1.0.6247.17495

### ISSUE THREAD

**Issue by jmenendezFKQ** [skttl/umbraco-doc-type-grid-editor#172]
Hello,

We are having an issue with your plugin in version 0.5.0 on Umbraco version 7.5.9 assembly: 1.0.6247.17495.

The problem we are having is with required fields: a user is are allowed to submit empty fields for parameters that are required in the DocType.

We are unable for various reasons to upgrade to a higher version of Umbraco, and the highest version of your plugin we can install on this instance is 0.5.0.

Any assistance would be helpful and appreciated.

**Comment by jmenendezFKQ** [comment]
This ticket has been open for two weeks. Can anyone please assist?

**Comment by skttl** [comment]
Hi @jmenendezFKQ 

There is a PR submitted that enables required fields for the v8 version.

I am not going to work on a soluton for the v7 version, but I'll leave it up for grabs, in case you or anyone else wants to try and make it work.

**Comment by skttl** [comment]
Closing this as v0 is unsupported
