### ISSUE TITLE
previewCssFilePath / previewJsFilePath returns 404

### ISSUE THREAD

**Issue by EmielD** [skttl/umbraco-doc-type-grid-editor#175]
**Umbraco version**: 8.4.0
**DTGE version**: 1.1.0

Created this this folder structure:

![image](https://user-images.githubusercontent.com/16267938/72806013-8edd2b00-3c54-11ea-9761-3679d74a194f.png)

The grid editor manifest:

```
{
      "name": "Brands",
      "alias": "gridBrands",
      "view": "/App_Plugins/DocTypeGridEditor/Views/doctypegrideditor.html",
      "render": "/App_Plugins/DocTypeGridEditor/Render/DocTypeGridEditor.cshtml",
      "icon": "icon-library color-blue",
      "config": {
        "allowedDocTypes": [ "gridBrands" ],
        "nameTemplate": "",
        "enablePreview": true,
        "overlaySize": "medium",
        "viewPath": "/Views/Partials/Grid/DocTypeGridEditor/",
        "previewViewPath": "/Views/Partials/Grid/DocTypeGridEditor/Previews/Cshtml/",
        "previewCssFilePath": "/Views/Partials/Grid/DocTypeGridEditor/Previews/Css/GridBrands.css",
        "previewJsFilePath": "/Views/Partials/Grid/DocTypeGridEditor/Previews/Js/GridBrands.js"
      }
}
```

Umbraco returns a 404 with the following requested url's:

```
/Views/Partials/Grid/DocTypeGridEditor/Previews/Css/GridBrands.css?umb__rnd=7c9be0a405d624343db752edea6d90a2

/Views/Partials/Grid/DocTypeGridEditor/Previews/Js/GridBrands.js?umb__rnd=7c9be0a405d624343db752edea6d90a2
```

File properties are all default (content / do not copy)

I've also tried removing the file names, hoping it would resolve them automaticly (as it seems to happen with the previewViewPath, which works just fine) though then I get a 404 simulair to the one above but of course without the file names:

```
/Views/Partials/Grid/DocTypeGridEditor/Previews/Css/?umb__rnd=7c9be0a405d624343db752edea6d90a2

/Views/Partials/Grid/DocTypeGridEditor/Previews/Js/?umb__rnd=7c9be0a405d624343db752edea6d90a2
```

What is going wrong here? Thanks!

**Comment by skttl** [comment]
Hi @EmielD 

This is because Umbraco (or `/Views/Web.config`) blocks all requests to files in the Views folder. You need to move your assets outside.

**Comment by EmielD** [comment]
> Hi @EmielD
> 
> This is because Umbraco (or `/Views/Web.config`) blocks all requests to files in the Views folder. You need to move your assets outside.

That did the trick, thanks!
