### ISSUE TITLE
When a DefaultDocTypeGridEditorSurfaceControllerType is set, a view for editorAlias is skipped

### ISSUE THREAD

**Issue by tompipe** [skttl/umbraco-doc-type-grid-editor#178]
When a grid editor has a view matching it's alias, DTGE activates that view before a view matching the content type alias, as per 

https://github.com/skttl/umbraco-doc-type-grid-editor/blob/1bdd3e32dc7e9caa2f8f98837e0ea72f2d7052fc/src/Our.Umbraco.DocTypeGridEditor/Web/Extensions/HtmlHelperExtensions.cs#L99-L109

However, when a default surface controller is registered, the editor alias is not passed through with the routeValues to the controller. 

If no action is found, then the fallback Index action will always render the view matching the content type alias, and not look for a view matching the editor alias first.

**Comment by skttl** [comment]
Hi @tompipe 

Isn't that what is done inhttps://github.com/skttl/umbraco-doc-type-grid-editor/blob/1bdd3e32dc7e9caa2f8f98837e0ea72f2d7052fc/src/Our.Umbraco.DocTypeGridEditor/Web/Extensions/HtmlHelperExtensions.cs#L61?

**Comment by tompipe** [comment]
Hmmm. I'll have to go back and double check what was going on 🥴

**Comment by skttl** [comment]
@tompipe did you find anything more? If not I'm going to close this...
