### ISSUE TITLE
Issue when loading redirected content

### ISSUE THREAD

**Issue by enkelmedia** [skttl/umbraco-doc-type-grid-editor#179]
Not sure if this is a issue with DocTypeGrid editor or if our setup is the problem here. Anyway, I figured I'll post an issue here to see if we have any way to get around it.

We're using a "Permanent Redirect"-feature much like this one:
https://our.umbraco.com/packages/backoffice-extensions/permanent-redirect/

When a node is redirected the fetching of preview-data will follow this redirect, ie. if I'm working on node 3389 there would be a number of requests to https://mysite.com/3389?dtgePreview=1 for fetching previews. 

The problem is that this node is redirected so the preview fetch would get the HTML content of the whole page in the redirect destination.

So one solution in our case would be to ignore the redirect if dtgePreview is present as a Querystring, but I'm also wondering if there is room for improvements around how the previews are fetched for DocTypeGrid editor? Is there any special reason for rendering /3389 also forcing us to have the ContentFinder for node id activated... can we get around this in some way?

**Comment by skttl** [comment]
The preview mechanism was changed on 0.6.0, so it now uses an Api controller to render the preview contens, like /umbraco/backoffice/DocTypeGridEditorApi/DocTypeGridEditorApi/GetPreviewMarkup?dtgePreview=1&pageId=1412. 

What version are you on?

**Comment by enkelmedia** [comment]
Ohhh, thats nice! We're on 0.5.0 at the moment... Is an upgrade straight forward?

**Comment by skttl** [comment]
Yes, you have to be on Umbraco 7.6 as a minimum though :)
