### ISSUE TITLE
Can you get a DTGE node by ID? (Umbraco 7)

### ISSUE THREAD

**Issue by AckmanDESU** [skttl/umbraco-doc-type-grid-editor#181]
I have two issues at the moment:

* There seems to be no way to get the current node's GUID. I saw `.GetKey()` being mentioned but it gives me an empty GUID.
* There seems to be no way to get the IPublishedContent node by using `Umbraco.TypedContent()` or something similar.

I need to access a node's properties from a controller called via AJAX. Is it possible?

**Comment by skttl** [comment]
Hi @AckmanDESU 

DTGE nodes is not content nodes, so you can't get them by their id's.

You need to get the containing node (the one with the grid, that has the DTGE inside), and then traverse the property to find the right node.

Their ids is not part of the IPublishedElement, but is located on the parent object in the grid editor.

**Comment by AckmanDESU** [comment]
So I would have to manually parse the grid's JSON and find the node? In that case, how would one identify the component I'm looking for? There's no ID nor GUID I can look for anyway. Would there be a  way to convert that data to an IPublishedContent node if I found it?

**Comment by skttl** [comment]
You can get it in your grid rendering, it is a property on the control object IIRC.

You can't get it in the DTGE partial though, unless you do some ViewDataDictionary magic :)

**Comment by AckmanDESU** [comment]
That would work I guess, shame there isn't a less workaround-ish way to do it.

But what about getting a PublishedNode out of it and being able to get properties without manually doing all the work? Is there a way or should I put it together?

Thanks for the quick replies.

**Comment by skttl** [comment]
There is methods in DTGE for getting IPublishedElement from the object in grid. Open up the source code, and see what you can do :)

Remember to share, someone might need it too :)
