### ISSUE TITLE
Exception during startup in Umbraco 8.6

### ISSUE THREAD

**Issue by Chris-N1** [skttl/umbraco-doc-type-grid-editor#183]
As far as I can tell this is related to DocTypeGridEditor -  it doesn't occur when the plugin isn't installed, using Umbraco 8.6.

During Umbraco boot on my dev machine, VS2019 breaks here:
![image](https://user-images.githubusercontent.com/46811766/78873863-6a1e7580-7a43-11ea-909a-a1da3202057e.png)

(The code is in LightInject.cs, so I assume it's related to Dependency Injection as this is a core part of Umbraco).

Because serviceType is null; this doesn't seem to prevent the package working (I can still add doctypes to the grid and they will still render). This causes more exceptions further on - if I get chance over the weekend I'll download the source and see if I can work out why and do a PR if I can fix it.

**Comment by skttl** [comment]
Hi @Chris-N1 

Did you get any further with this?

**Comment by Chris-N1** [comment]
@skttl  I did not sorry - a client's migrated site went live just around then and things have gone a bit intense since due to some issues in 8.6.1. 

I'm actually using DTGE on the client's site and not getting this issue when debugging, but I still get it on a much smaller site that I was trying to build - if nobody else is getting the error it may be related to my set up, so feel free to close this and I'll reopen it when I have more time?
