### ISSUE TITLE
Intrusive styling in preview?

### ISSUE THREAD

**Issue by lars-erik** [skttl/umbraco-doc-type-grid-editor#188]
![image](https://user-images.githubusercontent.com/350918/79567279-37642500-80b4-11ea-9585-949b5b2b4691.png)

Why?

**Comment by skttl** [comment]
Don't know why, it has been there for over 2 years :) d472d60022c7f59b4ce41165580a66eb4355a42c

What happens if you remove it?

**Comment by lars-erik** [comment]
Nothing unexpected. 😆

**Comment by skttl** [comment]
It is because `.umb-grid .umb-editor-placeholder` sets `text-align:center`. I'll move it into the css file, in stead and set it to `initial`.

**Comment by skttl** [comment]
Fixed in 975644b

**Comment by lars-erik** [comment]
@skttl The "initial" that's there now is still overriding any other styling. Can it be inherit? How do I reproduce the "wrong" alignment to see why this is?
