### ISSUE TITLE
Should we have an notification after each edit...? 

### ISSUE THREAD

**Issue by enkelmedia** [skttl/umbraco-doc-type-grid-editor#190]
As of today, I get this notification a lot when working in the grid:

![content saved](https://user-images.githubusercontent.com/1782524/80119749-6550da00-858a-11ea-91d8-12bc119be4b4.PNG)

It shows each time a save some changes on a DTGE-control, and they stay for a while so sometimes I have 2-3 of them at the same time.

I'm wondering if this is really needed? No other editor in the grid is reminding the editor to save the content?

**Comment by skttl** [comment]
Probably a side effect from saving the controls as blueprints. Should definitely be removed!

**Comment by enkelmedia** [comment]
I don’t really understand the “blue prints”-part :) But if you have some pointers I’d be happy to help out if you want to.

Cheers!

**Comment by skttl** [comment]
Hi @enkelmedia 

It's coming from #176, I think the notification is coming from the contentEditingHelper in https://github.com/skttl/umbraco-doc-type-grid-editor/blob/develop/src/Our.Umbraco.DocTypeGridEditor/Web/UI/App_Plugins/DocTypeGridEditor/Js/doctypegrideditor.controllers.js#L278. Need to investigate :)

**Comment by skttl** [comment]
Fixed in 
09acdd3
