### ISSUE TITLE
Infinite loading when doc type has a content template

### ISSUE THREAD

**Issue by OlePc** [skttl/umbraco-doc-type-grid-editor#192]
If I create an editor in package manifest (not using the built in Doc Type editor), and later add a content template for that editor, I get an infinate loading spinner in the dialog when trying to insert the editor.

![image](https://user-images.githubusercontent.com/8521882/80481479-cabe1580-8952-11ea-84b2-20dfa95fd518.png)

**STR:**
1. Create a doctype for the editor
2. Create a content template for the doctype
2. Register a new editor in package.manifest
3. Attempt to insert the editor in the grid
4. Notice that the dialog opens, the spinner keeps loading

Reproduced on blank Umbraco 8.6.1 and DTGE 1.2.1 (The bug is also present in 1.1 and 1.2, so it's not a new thing)

**Comment by skttl** [comment]
Hi @OlePc 

Thanks for the detailed description. Do you have any console errors?

**Comment by OlePc** [comment]
@skttl None. And the `GetContentTypes` call returns 200. So the bug is maybe around where the response from this call is handled.
