### ISSUE TITLE
You can't add NC items if an NC item is in clipboard

### ISSUE THREAD

**Issue by OlePc** [skttl/umbraco-doc-type-grid-editor#193]
If you have any NC item in the clipboard (doesn't matter if it's from a grid editor doc type or normal content), the modal where you choose whether to add an item from clipboard or a blank one never appears. Seems like a z index issue. The only way to move on, is to manually delete the `ls.umbClipboardService` key from the local storage from the browser.

STR:
1. Create a DTGE with a nested content property editor on it
2. Insert the editor in the grid, and click on the "Add Content" button. Now click on the "Copy" icon on top of the item you just added.
3. Now click "Add Content" again
4. Notice that the overlay backdrop is added, but the modal never appears
NB. I can actually get it to appear if I resize the browser a bit, and open and close the dialog a few times

Reproduced on Umbraco 8.6.1 with Starter Kit and DTGE 1.2.0 and 1.2.1.

**Comment by skttl** [comment]
This is a bug in core https://github.com/umbraco/Umbraco-CMS/issues/7754 that is going to be fixed in 8.7.0. I think there is a workaround posted in the issue, but haven't tried it myself.
