### ISSUE TITLE
Database hits when using Nested Content

### ISSUE THREAD

**Issue by skttl** [skttl/umbraco-doc-type-grid-editor#194]
The `FromEditor()` call in https://github.com/skttl/umbraco-doc-type-grid-editor/blob/develop/src/Our.Umbraco.DocTypeGridEditor/Helpers/DocTypeGridEditorHelper.cs#L68 causes SQL queries being fired from Nested Content, as it uses the DataTypeService to lookup the properties inside.

This has always been the case for Nested Content so nothing new.

But can we avoid it somehow in DTGE?

We could probably cache the the value of `ConvertValue` in the RuntimeCache in stead of RequestCache (found here https://github.com/skttl/umbraco-doc-type-grid-editor/blob/develop/src/Our.Umbraco.DocTypeGridEditor/Helpers/DocTypeGridEditorHelper.cs#L35) in stead, but that would require that we also clear this cache, and there are maybe other drawbacks.

![image](https://user-images.githubusercontent.com/3726467/80802468-b88ce300-8baf-11ea-97fa-dacf4d386458.png)

**Comment by enkelmedia** [comment]
So cool I just spent some hours to nail down why we saw these calls, it's indeed DTGE when having a Nested Content-property on it. I'll have a look to see what might be possible to do!

**Comment by enkelmedia** [comment]
Looking at this, the "id" taken as parameter here https://github.com/skttl/umbraco-doc-type-grid-editor/blob/693fb87071af8a9cec96e27d994468a0a331b9d3/src/Our.Umbraco.DocTypeGridEditor/Helpers/DocTypeGridEditorHelper.cs#L24 would be the "id" of the item in the grid, problem is that if one copies a node in the tree this id would still be the same on the newly created node.

This would mean that we would have to cache this property together with the id of the current page if I'm not miss-understanding something. I guess that this would not be a problem, cache the whole thing and kill this cache when something changes on that node. But our cache would also grow quite big over time.

**Comment by skttl** [comment]
Great that you are picking this up @enkelmedia 

I think this needs to be tested a lot, to make sure that it doesn't affect performance too much. If caches grow too big or something like that. Not sure my self how to do that though...

**Comment by enkelmedia** [comment]
That really true needs extensive testing and depending on the site of the site it might use a fair amount of memory.

I've updated the PR with some cache invalidation etc. The site that we're working on right now does not have any variants. It might be the cache that this would not work when a page have lang variants since the cache key only stores the page id. That would mean that the first rendered language would end up in the cache. 

I'm going to use this version on site now and follow the metrics, I'll keep you posted.

A "side track" on this one might be to see if there could be contribution made to the core to avoid this roundtrip to the DB as well?

**Comment by skttl** [comment]
Just a thought, would it make sense to take inspiration from the way Core handles Nested Content?
https://github.com/umbraco/Umbraco-CMS/blob/v8/contrib/src/Umbraco.Web/PropertyEditors/ValueConverters/NestedContentValueConverterBase.cs#L42

**Comment by skttl** [comment]
Nope, that won't work... just thought it might handle Nested Nested Content data in another way... :(

**Comment by skttl** [comment]
The more I am thinking of this, the more I think caching should be a responsibility of the implementor. If we add core-level caching of this I suspect that we will end up using loads of memory on every editor, or only cache certain editors (and then we are vulnerable to other parts that needs caching).

Caching can be implemented in the grid rendering by switching 
```
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
```

with

```
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.CachedPartial("grid/editors/base", (object)control, 3600)</text>
                        }
```

You can then add your own conditions for when to cache based on the `control`.

What do you think @enkelmedia ?

**Comment by enkelmedia** [comment]
Well, given the situation and that there is not "easy" solution to this at the moment it might be good to keep this up to the implementor. I've been running the fixes that I provided on my prod-site for a week now and we haven't had any issues but there is a memory footprint which might be something that should be up to each implementor to decide on.

I would be fine with not going forward with the solution from the PR, I do think that the "right" way to solve this would be to investigate if there is anything that can be contributed to Umbraco Core that would avoid the DB-roundtrips.

**Comment by skttl** [comment]
Closing this - as mentioned before I think we are going to use too much memory caching everything, and not really helping if only detecting Nested Content.

Besides - the block editor is imminent, and will likely obsolete DTGE. So I don't wan't to add too big changes now.
