### ISSUE TITLE
2 Element Types in same Nested Content freeze the Add content button in the grid layout

### ISSUE THREAD

**Issue by Emetico** [skttl/umbraco-doc-type-grid-editor#199]
Hi.

On a fresh Umbraco CMS 8.6.1 install and a fresh install of Doc Type Grid Editor 1.2.1. The Add content button, in the grid layout frezze, when using 2 Element Types in the same Nested Content.

[https://our.umbraco.com/packages/backoffice-extensions/doc-type-grid-editor/doc-type-grid-editor-feedback/102155-nested-content-with-2-element-types-freeze-the-add-content-button-in-grid-layout](https://our.umbraco.com/packages/backoffice-extensions/doc-type-grid-editor/doc-type-grid-editor-feedback/102155-nested-content-with-2-element-types-freeze-the-add-content-button-in-grid-layout)

**Comment by skttl** [comment]
This is a bug in core umbraco/Umbraco-CMS#7754 that is going to be fixed in 8.7.0. I think there is a workaround posted in the issue, but haven't tried it myself.

**Comment by skttl** [comment]
I added the workaround to the package in e36d42434cea9ea76b386df3d62ba56a85a9af30, so people not able to upgrade - or people eagerly waiting for 8.7.0 can have it working :)
