### ISSUE TITLE
"activeVariant.language is null"

### ISSUE THREAD

**Issue by mcl-sz** [skttl/umbraco-doc-type-grid-editor#201]
I've upgraded Umbraco 8.2.2 with DTGE 1.1 to Umbraco 8.6.1with DTGE1.2.2.

After upgrading to 1.2.2 i get the error "activeVariant.language is null" on line 155 in doctypegrideditor.controllers.js.

**Comment by inetzo** [comment]
I changed line 155 from

var culture = activeVariant ? activeVariant.language.culture : null;

to

var culture = activeVariant.language !== null ? activeVariant.language.culture : null;

This fixed it for me, de preview is now working again.

**Comment by Matthew-Wise** [comment]
Thats on me not checking well enough I'll get a PR submitted.
