### ISSUE TITLE
Contenttemplates are left behind when validation is not succesfull

### ISSUE THREAD

**Issue by inetzo** [skttl/umbraco-doc-type-grid-editor#202]
i use Umbraco 8.6.1 with DTGE 1.2.2.
When the validation of the a DTGE form is not succesfull, for example, because a required field has been left blank, the node under "Content Templates" is not getting deleted and stays behind.

**Comment by skttl** [comment]
They should be deleted by this line... https://github.com/skttl/umbraco-doc-type-grid-editor/blob/develop/src/Our.Umbraco.DocTypeGridEditor/Web/UI/App_Plugins/DocTypeGridEditor/Js/doctypegrideditor.controllers.js#L254

Needs to investigate this - if you'd like to help, it's appreciated :)

**Comment by skttl** [comment]
Found and fixed in d211de9cd58a12b5faa6f2cadf34af3a8223d6b2
