### ISSUE TITLE
EditorState changes structure after edit

### ISSUE THREAD

**Issue by jesperordrup** [skttl/umbraco-doc-type-grid-editor#206]
Seems that properties are moved from named properties to an array of properties?

Create some content using dtge. Use a dtge element with a text property "headline".
Save and refresh the page in backend.

From another property editor I can I can access the value like this:
```
var headline = editorState.current.variants[0].tabs[0].properties[0].value.sections[0].rows[0].areas[0].controls[0].value.value.headline;
```          

Update the dgte element with the text property. Now the properties are moved to an array

```
var headline = editorState.current.variants[0].tabs[0].properties[1].value;
```          

Is that a bug?

**Comment by skttl** [comment]
Could be, not sure if it's DTGE or Umbraco related though...

**Comment by skttl** [comment]
It does seem to mess around with the editorState. It looks to me like the editor state gets swapped from the nodes editorstate to the DTGE items editorstate once you submit the dialog.

I just tried adding a content picker too, to be able to open another infinite editor. And that one does the same. So I guess it's somewhere in the editorService in Umbraco that the editorState gets messed up.
