### ISSUE TITLE
Package Compatibility, Umbraco 8.6.x

### ISSUE THREAD

**Issue by enriquecapellan** [skttl/umbraco-doc-type-grid-editor#207]
Hi, I'm staring a new project using Umbraco 8.6 (The last one), but I've seen that Doc Type Grid Editor isn't 100% compatible whit that version.
What are the compatibility problems? 
Are you working to solve this?
Grate package btw, thanks.

**Comment by skttl** [comment]
It is compatible with 8.6 AFAIK. I have a few solutions running DTGE with 8.6

**Comment by c9mbundy** [comment]
I suspect that many people confuse the 'compatibility community feedback' on OurUmbraco with documented compatibility. It's a useless feature (worse than useless?) on OU as it doesn't tell you anything other than someone had an issue and decided to report it as  "Doesn't Work" and not the issue they encountered.
