### ISSUE TITLE
cropAlias working in View but not previewView.

### ISSUE THREAD

**Issue by mistyn8** [skttl/umbraco-doc-type-grid-editor#209]
`Model.BrandImgNode.GetCropUrl(width: 800, cropAlias: "Landscape")`
works in the View but not in previewView.

As soon as cropAlias: is introduced getCropUrl returns null/empty.

As I only needed crop at center point, changing aspect, I can work around it with

`m.Image.GetCropUrl(width:480, height:288)`

**Comment by skttl** [comment]
Hi @mistyn8 

Just tried this out in 8.7RC - and it works as expected. I get the defined crop both in preview and the frontend.

This is my test view
```cshtml
@inherits UmbracoViewPage<TestImageCropper>

<img src="@Model.Image.GetCropUrl(width:200, cropAlias:"testcrop")" />
```
