### ISSUE TITLE
Use of JS optional chaining operator breaks the grid editor in older browsers

### ISSUE THREAD

**Issue by xdjoshuaaz** [skttl/umbraco-doc-type-grid-editor#212]
PR #203 has introduced a syntax error for browsers that do not support the JS optional chaining operator, which includes IE11 and older versions of Safari on macOS and iOS.

https://caniuse.com/#feat=mdn-javascript_operators_optional_chaining

Code in reference:
[doctypegrideditor.controllers.js](https://github.com/skttl/umbraco-doc-type-grid-editor/blob/3cbe98df82b4e4e2f4405fda4e12e4bf231271b2/src/Our.Umbraco.DocTypeGridEditor/Web/UI/App_Plugins/DocTypeGridEditor/Js/doctypegrideditor.controllers.js#L154) lines 154-155.

**Comment by skttl** [comment]
Yes, but since Umbraco doesn't support IE11 and older versions of Safari, then this is not going to be a priority.
