### ISSUE TITLE
Don't include default grid-editor in package.manifest

### ISSUE THREAD

**Issue by lars-erik** [skttl/umbraco-doc-type-grid-editor#222]
For a lot of cells in our grids we can't really be bothered to select allowed grid-editors. It'll be a maintenance nightmare with the current way to configure the grid. In such cells the default doctype grid editor is available and shows way too many options with a non-contextual icon and title.

Would it be possible to somehow include the "default" config as a sample instead of a proper grid-editor in the bundled package.manifest?

Might be we'll just be treating a symptom of a "sickness" in the core grid config, but atm. I don't see an overcomable way to cure the decease. :P

**Comment by skttl** [comment]
Wouldn't that be a breaking change? I get your frustration, but I also feel that removing it will make it harder to learn DTGE.

Besides, with the coming of block editors, my opinion is that DTGE is slowly going to be obsolete.

**Comment by lars-erik** [comment]
Bah, I guess it would be breaking. I guess we can always just delete it every time we upgrade.  
I still dearly hope that the grid survives. Can't manage to keep any optimism for a grid-like block editor anytime soon even if you've done your two-column demo thing. Need it to be non-hacky. ;)

**Comment by skttl** [comment]
Block editors aside, as I mentioned, this would make it harder to learn and try out DTGE. So I won't remove this.

Besides, don't you have the same problems with the core grid editors? Or do you use those? I never do :)

**Comment by lars-erik** [comment]
I guess we do. Well, thoughts out of my mind. Close is NP. :)  
Tnx for the attention.
