### ISSUE TITLE
Variants support

### ISSUE THREAD

**Issue by lars-erik** [skttl/umbraco-doc-type-grid-editor#223]
I know I'm being a pr**k, but did you give any thoughts to allow segmentation within the DTGE dialog? 😁
Would be awesome to be able to personalize within the grid using uMarketingSuite...

**Comment by skttl** [comment]
That would require support for variants, wouldn't it?

**Comment by lars-erik** [comment]
Yes, I confuse variants and segments. ;)

**Comment by skttl** [comment]
This would probably require the grid it self to support variants. I'm open for PRs, but it's not something that I am going to work on :)

**Comment by lars-erik** [comment]
I don't think it requires the full grid to support it. We could introduce a drop-down on top of the settings dialog.  
I'll see about an experiment if I ever get time/motivation for this. Would be really cool!

**Comment by skttl** [comment]
I think the right way of handling this would be to port Vorto in some way, then we can also put the same functionality in Nested Content, Block List, media, members etc.

**Comment by skttl** [comment]
https://github.com/umco/umbraco-vorto/issues/123
