### ISSUE TITLE
V8 Block List property editor

### ISSUE THREAD

**Issue by Jojov11** [skttl/umbraco-doc-type-grid-editor#226]
Hi,

I created a Document Type (element) with the "**Block List**" property editor and when I try to use it in DTGE, I get this error in the console and the "infinite loading" visual ...
**Console error:** `angular.js Could not find umbVariantContent in the $scope chain.`

Does DTGE support this type of editor or is it a bug?

Umbraco version 8.9.1 ( clean installation )

Thanks.

**Comment by Jojov11** [comment]
**Update**: The problem is with rendering only. If I click on property name ( on the left sidebar ), I activate "Block List" selector.

**Comment by skttl** [comment]
Yes, I can see the missing variant support in DTGE is probably a problem with block lists. I don't understand how you got it activated anyway. Can you elaborate?

**Comment by Jojov11** [comment]
When I tried to record a video, I found out that it worked for me (by clicking on the property name) because I had a "Block list" property ( same ) added to the doctype ( on Page ). After deleting from the docType element "Block list" it no longer works at all.

How long will the fix take? It's pretty important to me.  :-)
Thanks.

**Comment by skttl** [comment]
So you clicked another block list property outside of your DTGE?

Btw, this is open source - you are very welcome to submit a PR with a fix if you need this fixed ASAP.

**Comment by Jojov11** [comment]
Not. I had the same "Block list" in DTGE as in the docType page where I inserted DTGE.

After clicking on the property name in DTGE, it probably activated an element from the page, no from DTGE. When I added item in "Block List", the content was displayed on the page not in DTGE.

I know it's open source, but I have no idea how this add-on works in the background. If I had a solution, I would send it here. :)
My question about the time of the fix was only for information purposes. :) I apologize if it was taken as pressure.

**Comment by AaronSadlerUK** [comment]
I am also having this issue with the block list editor.

**Comment by deMD** [comment]
I have been taking a look at this issue and it's pretty complicated to fix.

Currently the BlocklistEditor seems to be pretty hardcoded to only work as a root document type property or a nested property on a blocklist item. As it is now the scope tree in DTGE is missing the variantContent reference and I can't seem to find a way to make sure it is contained in the scope tree.

**Comment by skttl** [comment]
Thanks for looking into this @deMD. Sounds like something that needs fixing in Core.

**Comment by pariashiri1984** [comment]
how did you solve this problem? I have the same issue
