### ISSUE TITLE
Unable to save Nested Content node

### ISSUE THREAD

**Issue by skartknet** [skttl/umbraco-doc-type-grid-editor#230]
One of the doctypes we have configured includes a Nested Content property. This property only has one element type configured and this element has a few mandatory properties. If I enter all the properties, all works. But if I miss one of the mandatory properties, then I fix it then I can't save, I keep getting an error on the editor warning me about that something is wrong. The error message doesn't;t point to an specific property but to the whole item.

![image](https://user-images.githubusercontent.com/1685262/101698926-7412df80-3ace-11eb-8023-9e01b92e57bc.png)

I can see on the console that a call to PostSaveBlueprint is failing. The response from the server is:
`
{"id":1781,"udi":"umb://document-blueprint/55d34abeae9b4c96bdbb9e4a019db72f","icon":"icon-document","trashed":false,"key":"55d34abe-ae9b-4c96-bdbb-9e4a019db72f","parentId":-1,"path":"-1,1258,1781","variants":[{"name":"Dtge Temp: a02cce95-568f-4c63-bd68-35b48d16ea61","displayName":null,"tabs":[{"id":62,"active":true,"label":"Anchor","alias":"Anchor","open":true,"properties":[{"label":"Anchor Id","description":"Use this Id for \"Jump to section\" anchor link.","view":"textbox","config":{"maxChars":null},"hideLabel":false,"validation":{"mandatory":false,"mandatoryMessage":null,"pattern":null,"patternMessage":null},"readonly":false,"id":0,"dataTypeKey":"0cc0eba1-9960-42c9-bf9b-60e150b429ae","value":"","alias":"anchorId","editor":"Umbraco.TextBox","isSensitive":false,"culture":null,"segment":null}]},{"id":57,"active":false,"label":"Masonry Filter","alias":"Masonry Filter","open":true,"properties":[{"label":"Title","description":"This title will show above the Masonry Filter","view":"textbox","config":{"maxChars":null},"hideLabel":false,"validation":{"mandatory":false,"mandatoryMessage":null,"pattern":"","patternMessage":null},"readonly":false,"id":0,"dataTypeKey":"0cc0eba1-9960-42c9-bf9b-60e150b429ae","value":"","alias":"title","editor":"Umbraco.TextBox","isSensitive":false,"culture":null,"segment":null},{"label":"Page links","description":"","view":"nestedcontent","config":{"contentTypes":[{"ncAlias":"masonryElement","ncTabAlias":"Masonry Element","nameTemplate":"{{title}}"}],"minItems":null,"maxItems":null,"confirmDeletes":true,"showIcons":true,"hideLabel":false},"hideLabel":false,"validation":{"mandatory":false,"mandatoryMessage":null,"pattern":"","patternMessage":null},"readonly":false,"id":0,"dataTypeKey":"3a6ce867-8cd9-4687-bb1f-24b11db8cf46","value":[{"key":"38aa8a93-c4fb-427c-b63c-6d76c61caefe","name":"Item 1","ncContentTypeAlias":"masonryElement","title":"asd","subtitle":"","pageLinkType":"","image":"","mobileImage":"","blockColour":[],"link":[],"category":"","membersOnly":"0"}],"alias":"pageLinks","editor":"Umbraco.NestedContent","isSensitive":false,"culture":null,"segment":null},{"label":"Hide filter","description":"Set to true to hide the filter","view":"boolean","config":{"default":false,"showLabels":false,"labelOn":null,"labelOff":null},"hideLabel":false,"validation":{"mandatory":false,"mandatoryMessage":null,"pattern":"","patternMessage":null},"readonly":false,"id":0,"dataTypeKey":"92897bc6-a5f3-4ffe-ae27-f2e7e33dda49","value":"0","alias":"hideFilter","editor":"Umbraco.TrueFalse","isSensitive":false,"culture":null,"segment":null}]},{"id":112,"active":false,"label":"Hidden On Mobile or Desktop","alias":"Hidden On Mobile or Desktop","open":true,"properties":[{"label":"Hide on Mobile","description":"","view":"boolean","config":{"default":false,"showLabels":false,"labelOn":null,"labelOff":null},"hideLabel":false,"validation":{"mandatory":false,"mandatoryMessage":null,"pattern":"","patternMessage":null},"readonly":false,"id":0,"dataTypeKey":"92897bc6-a5f3-4ffe-ae27-f2e7e33dda49","value":"0","alias":"hideOnMobile","editor":"Umbraco.TrueFalse","isSensitive":false,"culture":null,"segment":null},{"label":"Hide On Desktop","description":"","view":"boolean","config":{"default":false,"showLabels":false,"labelOn":null,"labelOff":null},"hideLabel":false,"validation":{"mandatory":false,"mandatoryMessage":null,"pattern":"","patternMessage":null},"readonly":false,"id":0,"dataTypeKey":"92897bc6-a5f3-4ffe-ae27-f2e7e33dda49","value":"0","alias":"hideOnDesktop","editor":"Umbraco.TrueFalse","isSensitive":false,"culture":null,"segment":null}]}],"language":null,"segment":null,"state":"Draft","updateDate":"2020-12-10 09:45:59","createDate":"2020-12-10 09:45:59","publishDate":null,"releaseDate":null,"expireDate":null,"notifications":[]}],"owner":{"id":-1,"name":"admin"},"updater":{"id":-1,"name":"admin"},"contentTypeName":"Masonry Filter","isContainer":false,"isElement":true,"isChildOfListView":false,"treeNodeUrl":"/umbraco/backoffice/UmbracoTrees/ContentTree/GetTreeNode/55d34abeae9b4c96bdbb9e4a019db72f","contentTypeId":1258,"contentTypeKey":"ec4f772e-6898-4f62-9694-68bf6026f81c","contentTypeAlias":"masonryFilter","sortOrder":0,"updateDate":"2020-12-10 09:45:59","template":null,"templateId":0,"allowedTemplates":{},"documentType":{"alias":"masonryFilter","updateDate":"2020-08-21 11:12:04","createDate":"2020-08-21 11:12:04","description":null,"thumbnail":"folder.png","iconIsClass":true,"iconFilePath":"","thumbnailIsClass":false,"thumbnailFilePath":"/umbraco/images/thumbnails/folder.png","blueprints":{},"isContainer":false,"isElement":true,"name":"Masonry Filter","id":1258,"udi":"umb://member-type/ec4f772e68984f62969468bf6026f81c","icon":"icon-document","trashed":false,"key":"ec4f772e-6898-4f62-9694-68bf6026f81c","parentId":1061,"path":"-1,1061,1258","metaData":{}},"urls":[],"allowPreview":false,"allowedActions":["A"],"isBlueprint":true,"apps":[{"name":"Content","alias":"umbContent","weight":-100,"icon":"icon-document","view":"views/content/apps/content/content.html","viewModel":null,"active":false,"badge":null},{"name":"Info","alias":"umbInfo","weight":100,"icon":"icon-info","view":"views/content/apps/info/info.html","viewModel":null,"active":false,"badge":null}],"notifications":[],"ModelState":{"_Properties.pageLinks.invariant.null":["[{\"$id\":\"38aa8a93-c4fb-427c-b63c-6d76c61caefe\",\"$elementTypeAlias\":\"masonryElement\",\"ModelState\":{\"_Properties.pageLinkType.invariant.null.value\":[\"Value cannot be empty\"],\"_Properties.image.invariant.null.value\":[\"Value cannot be empty\"],\"_Properties.link.invariant.null.value\":[\"Value cannot be empty\"]}}]"]},"metaData":null}`

It looks like some variant values are empty?

Also, I have tracked the error to the line [where the editor creates a temporary blueprint](https://github.com/skttl/umbraco-doc-type-grid-editor/blob/9ea590568e924f4e00af0f7f70342bf31b3e5b95/src/Our.Umbraco.DocTypeGridEditor/Web/UI/App_Plugins/DocTypeGridEditor/Js/doctypegrideditor.controllers.js#L296)

The err value is undefined when this error happens.

**Comment by AaronSadlerUK** [comment]
This looks like issue #https://github.com/umbraco/Umbraco-CMS/issues/9341 or https://github.com/umbraco/Umbraco-CMS/issues/8954 in the core CMS itself
