### ISSUE TITLE
RTE overlaps label

### ISSUE THREAD

**Issue by AaronSadlerUK** [skttl/umbraco-doc-type-grid-editor#232]
The RTE overlaps the property label in the blade that slides out:

![image](https://user-images.githubusercontent.com/9937803/103789956-82560c00-5038-11eb-8aac-3064063172d4.png)

**Comment by AaronSadlerUK** [comment]
The same happens with nested content:

![image](https://user-images.githubusercontent.com/9937803/103790447-1f18a980-5039-11eb-844d-cf2d7c9ef3c5.png)

**Comment by skttl** [comment]
Which version is this in (both Umbraco + DTGE). Can you see what css is causing this?

**Comment by AaronSadlerUK** [comment]
I will have a play with the CSS is I get time later today or tomorrow.

This is Umbraco 8.8.1 and DTGE 1.2.6

**Comment by JakubHromada** [comment]
@AaronSadlerUK do you have the matryoshka package installed? We have seen the headings overlapping with the latest matryoshka package (0.7.0) installed on Umbraco 8.9.1 - maybe some Umbraco css clashing with the package css. Downgrading the package to 0.5.0 fixed the issue for us.

**Comment by AaronSadlerUK** [comment]
No, it seems the class `form-horizontal` is missing from the dialog.

As this as a wrapper div around the umb-property div and the styling works fine, struggling to find where this is in the views to fix with a PR.

![image](https://user-images.githubusercontent.com/9937803/103878999-2ab6af80-50cf-11eb-81e0-6f3a218b36cc.png)

**Comment by AaronSadlerUK** [comment]
PR #235 Seems to fix this 😊

**Comment by skttl** [comment]
I think the bug is in Umbraco. This float:left is IMO unnecessary, and removing it, fixes the problem.
image
