### ISSUE TITLE
Allowed doc types regex by default

### ISSUE THREAD

**Issue by AaronSadlerUK** [skttl/umbraco-doc-type-grid-editor#233]
I'm not sure if this is by design or a bug.

The allowed doc types is wildcard regex by default, which isn't made clear in the documentation.

For example by default:

`"allowedDocTypes": ['textDtgeBlock']`

matches both:

`textDtgeBlock`

and

`textDtgeBlockSettings`

I would expect by default only `textDtgeBlock` to match unless explicitly set to match both

**Comment by skttl** [comment]
Not sure either, but it would be a breaking change if changed. Maybe just update the docs to clarify?

**Comment by AaronSadlerUK** [comment]
Yeah that was my thought, updating the docs would be the best route.

See PR #234
