### ISSUE TITLE
Media Reference not picking up image

### ISSUE THREAD

**Issue by skartknet** [skttl/umbraco-doc-type-grid-editor#240]
Not sure if this is a Umbraco or DTGE issue. The problem is that we have included in the grid a doctype that uses nested content to create a list of items that include a media picker. The images selected with this picker are not being registered in the Media Reference section of the images as in use.
![media_reference](https://user-images.githubusercontent.com/1685262/108806978-4d594500-75f7-11eb-8a79-800b068b9321.gif)

**Comment by skttl** [comment]
Hmm... DTGE should just use Nested Contents own reference for this (https://github.com/skttl/umbraco-doc-type-grid-editor/blob/develop/src/Our.Umbraco.DocTypeGridEditor/ValueProcessing/DocTypeGridEditorDataValueReference.cs)

**Comment by skttl** [comment]
What media picker are you using?

Just tried a vanilla install with DTGE, creating a doctype containing nested content with a default media picker inside.

The value reference works as expected, digging into Nested Contents own value referencing, and then creating the reference between the media and the node.

**Comment by skartknet** [comment]
Thanks for your response @skttl , sorry I have been out of the radar! I'll try to investigate a bit further.
