### ISSUE TITLE
DTGE Temp content templates 

### ISSUE THREAD

**Issue by MathewMcPherson** [skttl/umbraco-doc-type-grid-editor#241]
Hi, I am working on a client project where we are experiencing an anomaly difficult to replicate. Within Umbraco Backoffice => Settings => Content Templates => [Some Doctype], there are multiple Content Templates with names 'dtge Temp: {GUID}'. It is unknown when or why these are created, but from what I gather they are used as "blueprints" by the doctype grid editor, and these blueprints are created on a save event. Perhaps there is a clean up function to remove these temp files once save has completed which is failing? 
![qa templates](https://user-images.githubusercontent.com/47421604/109805548-7f802d80-7c1b-11eb-958a-efb680996c08.PNG)

**Comment by skttl** [comment]
Which version?

**Comment by MathewMcPherson** [comment]
![image](https://user-images.githubusercontent.com/47421604/109985778-0a852480-7cfd-11eb-8e58-8b3be15d240b.png)
version 1.2.6

**Comment by BillyDigi** [comment]
Hi,

I also noticed this same issue on several of our production websites in the last couple of months. Version 1.2.3.
Don't know what causes it, I cannot replicate it myself to create these blueprints.

![Schermafbeelding 2021-03-12 080639](https://user-images.githubusercontent.com/28921505/111116456-58542500-8566-11eb-86bc-e96291231d2d.png)

**Comment by skttl** [comment]
Seems to have been fixed by #236. Will post a new release later
