### ISSUE TITLE
Package.Manifest specification for cell allowed grideditor - Min/Max cell size

### ISSUE THREAD

**Issue by mistyn8** [skttl/umbraco-doc-type-grid-editor#242]
Wondered if it would be possible to extend the allowed editors for cells to have an extra tier of setting in the manifest, such that allow all editors for a cell of size 6, could be sourced from a manifest setting of 

`manifest.minCellSize > grid cell size <= manifest.maxCellSize`

and then maintaining more granular add remove off those allowed ones, if allow all was unchecked?

finding it quite labour intensive when you get down to 6 column rows to specify allowed editors for each cell?

Any guidance on an implementation strategy?

**Comment by skttl** [comment]
I don't think it's possible with how the grid works, sorry.
