### ISSUE TITLE
Unable to Re-Order the Content of Grid Editor

### ISSUE THREAD

**Issue by sumedhashyam** [skttl/umbraco-doc-type-grid-editor#244]
I am unable to re-order the content entered inside the docType gridEditor.
When I am trying to do drag-and-drop, I am getting the issue as shown in attached image.
![image](https://user-images.githubusercontent.com/5002402/111131616-6e7dd780-859e-11eb-93c1-7a6d6da10ae1.png)

**Comment by skttl** [comment]
This must be a bug in the grid editor, not related to DTGE.

**Comment by sumedhashyam** [comment]
There is no bug in the Grid Editor as we are able to re-order the grid content in other projects. we guess the issue is with DTGE.

**Comment by c9mbundy** [comment]
Have you allowed the DocType editor to be valid for the grid row-cell you are trying to drag it into?

**Comment by sumedhashyam** [comment]
@c9mbundy 
Yes we have allowed all editors including DocType editor.
![image](https://user-images.githubusercontent.com/5002402/111264005-d25ed980-864c-11eb-9581-84c63742b7a1.png)
