### ISSUE TITLE
postsaveBlueprint 404

### ISSUE THREAD

**Issue by lori698** [skttl/umbraco-doc-type-grid-editor#249]
As an admin I dont have the problem but one of the clients who has editor access keeps getting 404

/office/backoffice/umbracoapi/content/postsaveBlueprint when trying to add/edit anything with an RTE

I am using Umbraco CMS 8.11.1 and Our.Umbraco.DocTypeGridEditor 1.2.6.

**Comment by skttl** [comment]
Hi @lori698 

Did you resolve the issue? Or can you still get the 404 error?
