### ISSUE TITLE
umb9.0.0-rc001 + dtge9.0.0-beta001 errors when adding content

### ISSUE THREAD

**Issue by leehowarth** [skttl/umbraco-doc-type-grid-editor#255]
Hi, I have been trying out the v9 beta of dtge editor with umb9.0.0-rc001 however every time I attempt to add any content into a grid editor that uses dtge there is a JS error that suggests the javascript files for dtge are not present / registered. 

![image](https://user-images.githubusercontent.com/917718/128246819-ca82459c-0175-4738-b191-17dd8975b2b6.png)

`umbraco-backoffice-js.js.v1:152 Error: [$controller:ctrlreg] http://errors.angularjs.org/1.8.0/$controller/ctrlreg?p0=Our.Umbraco.DocTypeGridEditor.GridEditors.DocTypeGridEditor
    at umbraco-backoffice-js.js.v1:32
    at umbraco-backoffice-js.js.v1:123
    at ea (umbraco-backoffice-js.js.v1:105)
    at p (umbraco-backoffice-js.js.v1:96)
    at g (umbraco-backoffice-js.js.v1:90)
    at umbraco-backoffice-js.js.v1:89
    at Object.link (umbraco-backoffice-js.js.v1:326)
    at umbraco-backoffice-js.js.v1:42
    at Ca (umbraco-backoffice-js.js.v1:114)
    at p (umbraco-backoffice-js.js.v1:98) "<div ng-if=\"control &amp;&amp; control.$editorPath\" ng-include=\"control.$editorPath\" class=\"umb-cell-{{control.editor.view}}\">"`

The grid editor then just displays as a blue bar. 

![image](https://user-images.githubusercontent.com/917718/128247242-63f7d74a-e20a-4754-a17c-d22f680ee426.png)

All of the JS/CSS files do appear to be present in the solution under App_Plugins so I believe the necessary files are present. 
![image](https://user-images.githubusercontent.com/917718/128247028-9f5499b0-0527-4051-ac30-d7cfb2f7e6dc.png)

I have been looking at the setup guide and think all is as it should be - https://github.com/skttl/umbraco-doc-type-grid-editor/blob/dev-v9/docs/developers-guide-v2.md#getting-set-up 

Are there any additional steps required for configuration? Could someone point me in the direction of what I may be missing?

**Comment by leehowarth** [comment]
We have now progressed onto umb9.0.0-rc003 and this issue is no longer presenting itself.

**Comment by rahulbpatel** [comment]
We are running into this issue when deploying our application.  Any idea why this might be still happening?  We're on RC004

**Comment by skttl** [comment]
Could be Smidge settings? Try upgrading to 9.0.0
