### ISSUE TITLE
umb 9.0.0-rc002 and dtge 9.0.0-beta001

### ISSUE THREAD

**Issue by mistyn8** [skttl/umbraco-doc-type-grid-editor#258]
Was working in rc001 but now get an error. :-(
```
An error occurred
A suitable constructor for type 'Our.Umbraco.DocTypeGridEditor.ValueProcessing.Collections.DocTypeGridEditorValueProcessorsCollection' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.

Exception Details
System.InvalidOperationException, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e: A suitable constructor for type 'Our.Umbraco.DocTypeGridEditor.ValueProcessing.Collections.DocTypeGridEditorValueProcessorsCollection' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.
```

not sure if this might be the case.. but Visual Studio when generating the constructor wraps a Func<> 

```
public DocTypeGridEditorValueProcessorsCollection(Func<IEnumerable<IDocTypeGridEditorValueProcessor>> items) : base(items)
        { }
```

Looks like builder collection base altered in Umbraco.Core.Composing...
https://github.com/umbraco/Umbraco-CMS/blob/fbbfcd84c78c24f2ba11ac9c212d8868599fbe4f/src/Umbraco.Core/Composing/BuilderCollectionBase.cs#L19

**Comment by mistyn8** [comment]
Created a PR #259 

Though might also want to move from IUmbracoContextAccessor to IUmbracoContextFactory? judging by https://umbracians.slack.com/archives/C06G5LWBV/p1629126578191300

**Comment by skttl** [comment]
Thanks!

You are probably right about Accessor  vs Factory.

I'll see if I can find some time in the weekend to test and merge :)




Den tor. 19. aug. 2021 kl. 16.59 skrev Mike Chambers <
***@***.***>:

**Comment by enashnash** [comment]
@skttl did you manage to test this? We're having the same issue.

**Comment by leehowarth** [comment]
We have just been trying Umbraco v9 RC3 with the latest beta of doctype grid editor and are also encountering the exception 

Our.Umbraco.DocTypeGridEditor.ValueProcessing.Collections.DocTypeGridEditorValueProcessorsCollection' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.

**Comment by javz3** [comment]
Have the same situation as @leehowarth 

Any ETA @skttl ? Or anything we can do to help with this?

Thanks

**Comment by leehowarth** [comment]
@javz3 I have a workaround for the moment to use doctype grid editor in Umbraco v9 (rc003).  I have directly cloned the repo and directly referenced it within my project and removed the NuGet reference for now. Once the v9 package is ready I will change it back to the NuGet reference. 

The work @mistyn8 has done in [PR 259](https://github.com/skttl/umbraco-doc-type-grid-editor/pull/259) is pretty much all that is required with the addition of just upgrading the Umbraco references to the latest pre-release versions. You can just clone [/umbraco-doc-type-grid-editor/tree/feature/rc002](https://github.com/mistyn8/umbraco-doc-type-grid-editor/tree/feature/rc002), upgrade the Umbraco references and then reference in your project as needed. 

![image](https://user-images.githubusercontent.com/917718/133335156-cf5dee36-615a-40d9-b9bb-04eb8b0862aa.png)

@skttl I agree with the comment from @javz3 on if there is anything that can be done to help. Happy to assist myself if there any tasks you want help with.

**Comment by skttl** [comment]
Hi @leehowarth 

Thanks for testing #259, I need to find some time to do a release. Hopefully I can get it out this weekend!

**Comment by skttl** [comment]
@leehowarth finally got around to releasing a new RC :) https://www.nuget.org/packages/Our.Umbraco.DocTypeGridEditor/9.0.0-rc001

**Comment by leehowarth** [comment]
Thanks @skttl  I will migrate over the the nuget package shortly.
