### ISSUE TITLE
Custom Controllers umbv9

### ISSUE THREAD

**Issue by sgerme** [skttl/umbraco-doc-type-grid-editor#271]
Hi
I am trying to import a v8 DTGE model.
I was using a lot the possibility to have custom Doc Types into grid. 

I've changed the Controllers from : 
 BannerSurfaceController: DocTypeGridEditorSurfaceController

<img width="607" alt="image" src="https://user-images.githubusercontent.com/58856310/150970462-94ea524e-c29f-4a74-aff3-63764370a0f1.png">

to : 
BannerDocTypeGridEditorViewComponent : DocTypeGridEditorViewComponent

public IViewComponentResult Invoke(dynamic model, string viewPath)

But while loading every single page stops on  :

InvalidOperationException: View component 'events.core.Controllers.Blocks.BannerDocTypeGridEditorViewComponent' must have exactly one public method named 'InvokeAsync' or 'Invoke'.

Do you have an idea ?

Thanks

**Comment by skttl** [comment]
As the error states, you must have exactly one public method named InvokeAsync or Invoke. This is the method used for rendering.

https://github.com/skttl/umbraco-doc-type-grid-editor/blob/dev-v9/docs/developers-guide-v2.md#doctypegrideditorviewcomponent

**Comment by sgerme** [comment]
isn't it what I 've wrote ? 
BannerDocTypeGridEditorViewComponent : DocTypeGridEditorViewComponent

public IViewComponentResult Invoke(dynamic model, string viewPath) { ... }
