### ISSUE TITLE
Issues with Custom Controllers / View Components

### ISSUE THREAD

**Issue by sgerme** [skttl/umbraco-doc-type-grid-editor#272]
Hi

So after yesterday's issue, I've downloaded the solution to understand a bit more.

1/ the DocTypeGridEditor.ViewComponents.DocTypeGridEditorViewComponent { }  is not marked as virtual
So we can't override it. that's why , when you create your own ViewComponent and inherits from this class, it throws an error 

_"InvalidOperationException: View component '.... .BannerDocTypeGridEditorViewComponent' must have exactly one public method named 'InvokeAsync' or 'Invoke'._ 

2/ the views have to be available within the folder "Views/Partials/grid/editors/DocTypeGridEditor" , because before loading it, DocTypeGridEditor goes and check if it exists. 
When upgrading from umbv8 , I had Controllers named {alias}SurfaceController inheriting DocTypeGridEditorSurfaceController, and I would get the view from a path I would determine (/view/blocks, for me). Since all my views were in the wrong folder, the ViewsExist() Method couldn't find them.
If you have the problem, you'll find a log error saying :
Failed rendering DocTypeGridEditorItem / Could not get viewpath ...

Good luck with upgrading

Thanks

**Comment by skttl** [comment]
Hi @sgerme, you shouldn't inherit from `DocTypeGridEditorViewComponent`, just `ViewComponent`.

The view path is configured in your manifest https://github.com/skttl/umbraco-doc-type-grid-editor/blob/dev-v9/docs/developers-guide-v2.md#configuring-the-doc-type-grid-editor
