### ISSUE TITLE
MultiUrlPicker with min:0 max:1 throws null reference exception if nothing selected

### ISSUE THREAD

**Issue by mistyn8** [skttl/umbraco-doc-type-grid-editor#276]
![image](https://user-images.githubusercontent.com/12418214/155511993-3d74a9b4-1fbd-43ad-9780-6c56fd36983d.png)
![image](https://user-images.githubusercontent.com/12418214/155512050-c3190c5f-c69c-43f5-932c-6155f2f9534e.png)

I've tried the same outside of dtge and this correctly returns null, so maybe a convertor issue with dtge?
![image](https://user-images.githubusercontent.com/12418214/155512543-f16d6893-5c37-46e3-b892-11fe595a6e95.png)

Any ideas other than the try, catch (and disabling break on System.NullReferenceExceptions in vs2022)

**Comment by Nashuim** [comment]
I'm also getting this issue with the MultiUrlPicker.
It seems that the converter for the Links in Umbraco now expects those to either be null or have a value but the DocTypeGridEditor converter is returning an empty string which gets parsed into null and causes this issue.

**Comment by mistyn8** [comment]
My mistake it was also the multiUrlPicker for me.. not the mntp.
Think it's resolved with a custom value processor...
``` csharp
using Umbraco.Cms.Core;
using Our.Umbraco.DocTypeGridEditor.Helpers;
using Umbraco.Cms.Core.Composing;
using Umbraco.Cms.Core.DependencyInjection;
using Our.Umbraco.DocTypeGridEditor.ValueProcessing;
using Newtonsoft.Json;
using System.Linq;

namespace www.Extensions.Dtge
{
    public class UmbracoMultiUrlPickerValueProcessor : IDocTypeGridEditorValueProcessor
    {
        public bool IsProcessorFor(string propertyEditorAlias) => propertyEditorAlias.Equals(Constants.PropertyEditors.Aliases.MultiUrlPicker);

        public object ProcessValue(object value)
        {


            if (value == null)
            {
                // When the value is null, we need to fake an empty enumerable since this is
                // how Umbraco would store an empty "Umbraco.MultiUrlPicker"-property.
                return Enumerable.Empty<object>();
            }

            // Returns a string-version of the JArray that DTGE would pass.
            return value;
        }
    }

    public class TsdDocTypeGridEditorComposer : IComposer
    {
        public void Compose(IUmbracoBuilder builder)
        {
            builder.DocTypeGridEditorValueProcessors().Append<UmbracoMultiUrlPickerValueProcessor>();
        }
    }
}
```

**Comment by AlexanderWagner82** [comment]
I recently upgraded a clients Umbraco from 8.17 to 8.18 and I experience this problem there as well (using dtge 1.2.9). Could you provide a fix for Umbraco 8.18 as well?

**Comment by fabio-rocha** [comment]
I had the same issue when upgradind to 8.18.
I had to rollback to 8.17.

**Comment by giordanop** [comment]
I have temporary fixed in this way, but of course a package update would be preferable.

``` 
    var linkProperty= model.GetProperty("link");
    Link link = null;
    if (linkProperty.HasValue())
    {
        link = linkProperty.GetValue() as Link;
    }
```

**Comment by skttl** [comment]
Can anyone test if there are other "multiple" editors that does the same? I saw that Multinode tree picker was doing the same. If anyone can check content picker and media picker, it would be nice.

**Comment by skttl** [comment]
It breaks if you have pickers inside Nested Content inside DTGE too 😖

**Comment by skttl** [comment]
Another workaround (that works with Nested Content in DTGEs), is to replace the value converter for the multiurl picker with this one:

```cs
using System.Linq;
using Umbraco.Core;
using Umbraco.Core.Composing;
using Umbraco.Core.Logging;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Core.PropertyEditors;
using Umbraco.Web.Models;
using Umbraco.Web.PropertyEditors;
using Umbraco.Web.PublishedCache;

namespace myproject
{
    public class Startup : IUserComposer
    {
        public void Compose(Composition composition)
        {
            //If the type is accessible (not internal) you can deregister it by the type:
            composition.PropertyValueConverters().Remove<Umbraco.Web.PropertyEditors.ValueConverters.MultiUrlPickerValueConverter>();

        }
    }

    public class MultiUrlPickerValueConverter : Umbraco.Web.PropertyEditors.ValueConverters.MultiUrlPickerValueConverter
    {
        public MultiUrlPickerValueConverter(IPublishedSnapshotAccessor publishedSnapshotAccessor, IProfilingLogger proflog) : base(publishedSnapshotAccessor, proflog)
        {
        }

        public override object ConvertIntermediateToObject(IPublishedElement owner, IPublishedPropertyType propertyType, PropertyCacheLevel referenceCacheLevel, object inter, bool preview)
        {
            var maxNumber = propertyType.DataType.ConfigurationAs<MultiUrlPickerConfiguration>().MaxNumber;

            if (string.IsNullOrWhiteSpace(inter?.ToString()))
            {
                return maxNumber == 1 ? null : Enumerable.Empty<Link>();
            }

            return base.ConvertIntermediateToObject(owner, propertyType, referenceCacheLevel, inter, preview);
        }
    }
}
```

**Comment by AlexanderWagner82** [comment]
@skttl Awesome! Your work around works great! I'll use it until the package has been updated

**Comment by skttl** [comment]
I won't fix this in the package, as it would require too much. The thing is, that at breaks inside Nested Content too, so the ValueProcessor mentioned by @mistyn8 needs to look inside those too - and potentially nested content items inside nested content items.

So it needs to be fixed in Umbraco - and until then, the extended value converter is the workaround.
