### ISSUE TITLE
compatibility issue on radio button list

### ISSUE THREAD

**Issue by mitraganesh** [skttl/umbraco-doc-type-grid-editor#281]
I Have upgraded my v7.15.7 site to v8.5.4 but some compatibility issues come up for DTGE v0.6.1 like no value selected for radio button list under nested content on edit mode. No console error. 

Is there anyone encounter this issue?

**Comment by skttl** [comment]
Did you upgrade DTGE too? It needs to be on 1.x for Umbraco 8

**Comment by tormnator** [comment]
Disclaimer, I'm not yet 100% sure about the following. There's a U7 - U8 migration of RadioButtonList and similar "prevalues" which changes the stored value from being an integer to it being a string value. What I think is happening is that this migration is not able to "reach into" the DTGE json contents, and hence when U8 (and later) reads the value of a RadioButtonList property (in an embedded DTGE document) it expects that string value, but finds the non-migrated integer value. The result is none of the radio buttons are selected. Selecting a value in the backoffice and saving the document fixes it (but that of course is a cumbersome work around on a large site).

If I'm correct, I'm in need of a fix for this as well. I'll probably write my own migration/fix code which will iterate into site contents and properties and fix incorrect values. But it would be nice if someone already has implemented a DTGE aware migrator.

**Comment by c9mb** [comment]
Perhaps to do with the way the U7 version of DTGE stored indexed values? I know it was also incompatible with Umbraco-Deploy.
